//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDesk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplainStatu
    {
        public int id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> complain_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public string replay { get; set; }
    
        public virtual Complain Complain { get; set; }
        public virtual Status Status { get; set; }
    }
}
