//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDesk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public Complain()
        {
            this.ComplainStatus = new HashSet<ComplainStatu>();
        }
    
        public int id { get; set; }
        public Nullable<int> org_id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> inserted_date { get; set; }
        public Nullable<System.DateTime> complain_date { get; set; }
        public Nullable<int> system_id { get; set; }
        public Nullable<int> complain_type_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public string complain_text { get; set; }
        public string document_url { get; set; }
        public string document_name { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public string replay { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<ComplainStatu> ComplainStatus { get; set; }
        public virtual ComplainType ComplainType { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual Status Status { get; set; }
        public virtual SystemModule SystemModule { get; set; }
    }
}
