//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDesk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public Organisation()
        {
            this.Complains = new HashSet<Complain>();
            this.QAs = new HashSet<QA>();
            this.SystemModules = new HashSet<SystemModule>();
        }
    
        public int id { get; set; }
        public string org_name { get; set; }
        public string service_type { get; set; }
    
        public virtual ICollection<Complain> Complains { get; set; }
        public virtual ICollection<QA> QAs { get; set; }
        public virtual ICollection<SystemModule> SystemModules { get; set; }
    }
}
