//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDesk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA
    {
        public int id { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public Nullable<System.DateTime> ask_date { get; set; }
        public Nullable<System.DateTime> answer_date { get; set; }
        public string answer_user_id { get; set; }
        public string question_user_id { get; set; }
        public string question_file { get; set; }
        public string answer_file { get; set; }
        public Nullable<int> org_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
