//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDesk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Complains = new HashSet<Complain>();
            this.ComplainStatus = new HashSet<ComplainStatu>();
        }
    
        public int id { get; set; }
        public string status_value { get; set; }
        public string label { get; set; }
        public string is_client { get; set; }
    
        public virtual ICollection<Complain> Complains { get; set; }
        public virtual ICollection<ComplainStatu> ComplainStatus { get; set; }
    }
}
