//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDesk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemModule
    {
        public SystemModule()
        {
            this.Complains = new HashSet<Complain>();
            this.SystemModule1 = new HashSet<SystemModule>();
        }
    
        public int id { get; set; }
        public Nullable<int> organisation_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string name { get; set; }
        public Nullable<bool> is_module { get; set; }
        public Nullable<bool> is_enabled { get; set; }
    
        public virtual ICollection<Complain> Complains { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<SystemModule> SystemModule1 { get; set; }
        public virtual SystemModule SystemModule2 { get; set; }
    }
}
